use std::fs;
use std::path::Path;

use chrono::Utc;

use crate::error::Result;
use crate::storage::SavedCrate;

pub fn generate_index(output_dir: &Path, crates: &[SavedCrate]) -> Result<()> {
    let date = Utc::now().format("%Y-%m-%d").to_string();
    let mut sorted = crates.to_vec();
    sorted.sort_by(|a, b| a.name.cmp(&b.name).then(a.version.cmp(&b.version)));

    let fallback_count = sorted.iter().filter(|c| c.is_fallback).count();
    let total_files: usize = sorted.iter().map(|c| c.files.len()).sum();

    let mut content = String::new();
    content.push_str("<!-- This file is auto-generated by ai-fdocs. Do not edit manually. -->\n");
    content.push_str(&format!("<!-- Generated: {date} -->\n\n"));
    content.push_str("# Vendor Documentation Index (Rust)\n\n");
    content.push_str("## Summary\n\n");
    content.push_str(&format!(
        "- Crates: {}\n- Files: {}\n- Fallback refs used: {}\n\n",
        sorted.len(),
        total_files,
        fallback_count
    ));

    if sorted.is_empty() {
        content.push_str("*No crates synced yet.*\n");
    } else {
        content.push_str("## Quick navigation\n\n");
        for saved in &sorted {
            content.push_str(&format!(
                "- [{}@{}](#{})\n",
                saved.name,
                saved.version,
                section_id(saved)
            ));
        }
        content.push('\n');

        for saved in &sorted {
            content.push_str(&format!("<a id=\"{}\"></a>\n", section_id(saved)));
            if saved.is_fallback {
                content.push_str(&format!(
                    "## {}@{} ⚠️ (fetched from `{}`, no tag for v{})\n\n",
                    saved.name, saved.version, saved.git_ref, saved.version
                ));
            } else {
                content.push_str(&format!("## {}@{}\n\n", saved.name, saved.version));
            }

            if !saved.ai_notes.trim().is_empty() {
                content.push_str(&format!("**AI Notes:** {}\n\n", saved.ai_notes.trim()));
            }

            if saved.files.is_empty() {
                content.push_str("**Files:** _No files saved._\n\n");
            } else {
                let file_links: Vec<String> = saved
                    .files
                    .iter()
                    .map(|f| format!("[{f}]({}@{}/{})", saved.name, saved.version, f))
                    .collect();
                content.push_str(&format!("**Files:** {}\n\n", file_links.join(", ")));
            }
        }
    }

    fs::create_dir_all(output_dir)?;
    fs::write(output_dir.join("_INDEX.md"), content)?;

    Ok(())
}

fn section_id(saved: &SavedCrate) -> String {
    format!("{}-{}", saved.name, saved.version)
        .to_lowercase()
        .chars()
        .filter(|c| c.is_ascii_alphanumeric() || *c == '-' || *c == '_')
        .collect()
}

#[cfg(test)]
mod tests {
    use super::section_id;
    use crate::storage::SavedCrate;

    #[test]
    fn section_id_normalizes_crate_name_and_version() {
        let crate_info = SavedCrate {
            name: "serde_json".to_string(),
            version: "1.0.145".to_string(),
            git_ref: "v1.0.145".to_string(),
            is_fallback: false,
            files: vec![],
            ai_notes: String::new(),
        };

        assert_eq!(section_id(&crate_info), "serde_json-10145");
    }
}
