use std::fs;
use std::path::Path;

use chrono::Utc;

use crate::error::Result;
use crate::storage::SavedCrate;

pub fn generate_index(output_dir: &Path, crates: &[SavedCrate]) -> Result<()> {
    let date = Utc::now().format("%Y-%m-%d").to_string();

    let mut content = String::new();
    content.push_str("<!-- This file is auto-generated by ai-fdocs. Do not edit manually. -->\n");
    content.push_str(&format!("<!-- Generated: {date} -->\n\n"));
    content.push_str("# Vendor Documentation Index (Rust)\n\n");

    if crates.is_empty() {
        content.push_str("*No crates synced yet.*\n");
    }

    for saved in crates {
        if saved.is_fallback {
            content.push_str(&format!(
                "## {}@{} ⚠️ (fetched from `{}`, no tag for v{})\n\n",
                saved.name, saved.version, saved.git_ref, saved.version
            ));
        } else {
            content.push_str(&format!("## {}@{}\n\n", saved.name, saved.version));
        }

        if !saved.ai_notes.trim().is_empty() {
            content.push_str(&format!("**AI Notes:** {}\n\n", saved.ai_notes.trim()));
        }

        if !saved.files.is_empty() {
            let file_links: Vec<String> = saved
                .files
                .iter()
                .map(|f| format!("[{f}]({}@{}/{})", saved.name, saved.version, f))
                .collect();
            content.push_str(&format!("**Files:** {}\n\n", file_links.join(", ")));
        }
    }

    fs::create_dir_all(output_dir)?;
    fs::write(output_dir.join("_INDEX.md"), content)?;

    Ok(())
}
