import { writeFileSync } from "node:fs";
import { join } from "node:path";

export interface SummaryData {
  packageName: string;
  version: string;
  repo: string;
  gitRef: string;
  isFallback: boolean;
  aiNotes: string;
  files: SummaryFile[];
}

export interface SummaryFile {
  flatName: string;
  originalPath: string;
  sizeBytes: number;
}

export function generateSummary(pkgDir: string, data: SummaryData): void {
  const date = new Date().toISOString().split("T")[0];

  let content = "";
  content += "<!-- Auto-generated by ai-fdocs. Do not edit. -->\n";
  content += `<!-- Generated: ${date} -->\n\n`;
  content += `# ${data.packageName}@${data.version}\n\n`;

  content += `**Source:** [github.com/${data.repo}](https://github.com/${data.repo}) @ \`${data.gitRef}\``;
  if (data.isFallback) {
    content += " ⚠️ *(fallback — no tag found for this version)*";
  }
  content += "\n\n";

  if (data.aiNotes) {
    content += "## AI Notes\n\n";
    content += `${data.aiNotes.trim()}\n\n`;
  }

  content += "## Files\n\n";
  if (data.files.length === 0) {
    content += "*No files fetched.*\n\n";
  } else {
    content += "| File | Original Path | Size |\n";
    content += "|------|--------------|------|\n";
    for (const file of data.files) {
      const size = file.sizeBytes > 1024 ? `${(file.sizeBytes / 1024).toFixed(1)}KB` : `${file.sizeBytes}B`;
      content += `| [${file.flatName}](${file.flatName}) | \`${file.originalPath}\` | ${size} |\n`;
    }
    content += "\n";
  }

  writeFileSync(join(pkgDir, "_SUMMARY.md"), content, "utf-8");
}
